Repository fga-eps-mds/2019.1-ADA-github, pull requests merged in 2019-06, with the labels that each got.

#11 #211 Refatorar GitHub
  api/.coveragerc
  api/github/__init__.py
  api/github/branches/utils.py
  api/github/branches/views.py
  api/github/find_project_collaborators/__init__.py
  api/github/find_project_collaborators/error_messages.py
  api/github/find_project_collaborators/utils.py
  api/github/find_project_collaborators/views.py
  api/github/issue/utils.py
  api/github/issue/views.py
  api/github/pull_request/utils.py
  api/github/pull_request/views.py
  api/github/release/utils.py
  api/github/release/views.py
  api/github/tests/base.py
  api/github/tests/jsonschemas/find_project_collaborators/__init__.py
  api/github/tests/jsonschemas/find_project_collaborators/schemas.py
  api/github/tests/jsonschemas/github_utils/__init__.py
  api/github/tests/jsonschemas/github_utils/schemas.py
  api/github/tests/jsonschemas/issue/schemas.py
  api/github/tests/jsonschemas/webhooks/__init__.py
  api/github/tests/jsonschemas/webhooks/schemas.py
  api/github/tests/jsonschemas/webhooks/webhook_jsons.py
  api/github/tests/test_branches.py
  api/github/tests/test_find_project_collaborators.py
  api/github/tests/test_github_utils.py
  api/github/tests/test_issue.py
  api/github/tests/test_pull_request.py
  api/github/tests/test_release.py
  api/github/tests/test_user.py
  api/github/tests/test_webhook.py
  api/github/user/utils.py
  api/github/user/views.py
  api/github/utils/error_messages.py
  api/github/utils/github_utils.py
  api/github/webhook/views.py
  api/github/webhook/webhook_utils.py
  docker-compose.yml
Labels: bug

#13 US25 - Eu, como usuário, desejo receber notificação de revisão de Pull Requests
  api/github/tests/test_webhook.py
  api/github/webhook/views.py
  api/github/webhook/webhook_utils.py
Labels: enhancement

#14 US25 Hotfix - Change review pull requests messages
  api/github/webhook/views.py
Labels: bug

#21 266 Mockar Serviço GitHub
  api/github/contributor_issues/utils.py
  api/github/tests/base.py
  api/github/tests/jsonschemas/contributor_issues/schemas.py
  api/github/tests/test_branches.py
  api/github/tests/test_contributor_issues.py
  api/github/tests/test_find_project_collaborators.py
  api/github/tests/test_issue.py
  api/github/tests/test_pull_request.py
  api/github/tests/test_release.py
  api/github/tests/test_user.py
  api/github/tests/test_webhook.py
  api/github/user/utils.py
  api/github/user/views.py
Labels: enhancement

#28 #293 Atualizar o Community profile do repositório ADA-Github
  .github/ISSUE_TEMPLATE/issue-template.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  pull_request_template.md
Labels: Documentação

#29 Refatorar Botão
  api/github/tests/jsonschemas/user/schemas.py
  api/github/tests/test_user.py
  api/github/user/utils.py
  api/github/user/views.py
Labels: enhancement

#31 HotFix organization repository and delete webhook
  api/github/contributor_issues/views.py
  api/github/tests/test_contributor_issues.py
  api/github/tests/test_user.py
  api/github/user/utils.py
  api/github/user/views.py
  api/github/webhook/webhook_utils.py
Labels: bug
